version: "3"

services:
    app:
        build: .
        volumes:
            # really should put the go src in a subdirectory so we don't have
            # everything in the docker container
            - ".:/go/src/app"
        ports:
            - 8000
        links:
            - psql

    psql:
        image: postgres
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
            POSTGRES_DB: shakespeare
        volumes:
            # initialize shakespeare data
            - "./psql:/docker-entrypoint-initdb.d"
        ports:
           - 5432
